### ISSUE TITLE
调用插件的onCreate的时候NP

### ISSUE THREAD

**Issue by tinghaoMa** [liuguangli/ProxyPluginActivityDemo#1]
super.onCreate(savedInstanceState);
这里直接就异常了 导致反射异常
05-29 15:00:25.843 11371-11371/activity.plugin.proxy.demo.com.proxypluginactivitydemo W/System.err: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.plugin.PluginProxyActivity.invokePluginOnCreate(PluginProxyActivity.java:79)
        at com.plugin.PluginProxyActivity.onCreate(PluginProxyActivity.java:32)
05-29 15:00:25.844 11371-11371/activity.plugin.proxy.demo.com.proxypluginactivitydemo W/System.err:     at android.app.Activity.performCreate(Activity.java:6999)
        at android.app.Activity.performCreate(Activity.java:6990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
05-29 15:00:25.845 11371-11371/activity.plugin.proxy.demo.com.proxypluginactivitydemo W/System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-29 15:00:25.846 11371-11371/activity.plugin.proxy.demo.com.proxypluginactivitydemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
    Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.ActivityInfo.parentActivityName' on a null object reference
        at android.app.Activity.onCreate(Activity.java:994)
        at activity.plugin.proxy.demo.com.apkbeloaded.MainActivity.onCreate(MainActivity.java:14)
05-29 15:00:25.847 11371-11371/activity.plugin.proxy.demo.com.proxypluginactivitydemo W/System.err: 	... 16 more

**Comment by tinghaoMa** [comment]
人呢？
